import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';

function isAdmin(req: NextRequest) {
  return !!process.env.ADMIN_PASSWORD &&
    req.cookies.get('admin_token')?.value === process.env.ADMIN_PASSWORD;
}

const TOOLS = [
  { name:'Metasploit',      icon:'🛡️', category:'Exploitation',       language:'Ruby',       stars:'34.2k', description:'The world\'s most-used penetration testing framework — 2,300+ exploits across every major platform.',       githubUrl:'https://github.com/rapid7/metasploit-framework',           demoUrl:null,                                              gradient:'linear-gradient(135deg,#7f1d1d,#5a1313)', order:0 },
  { name:'Nmap',            icon:'🔍', category:'Reconnaissance',      language:'C / Lua',    stars:'10.1k', description:'The iconic "Network Mapper" — port scanning, OS detection, and scripting engine used by every pentester.', githubUrl:'https://github.com/nmap/nmap',                             demoUrl:'https://nmap.org',                                gradient:'linear-gradient(135deg,#1e3a8a,#1a3270)', order:1 },
  { name:'SQLMap',          icon:'💉', category:'Exploitation',       language:'Python',     stars:'32.8k', description:'Automatic SQL injection and database takeover tool. Supports MySQL, Oracle, PostgreSQL, MSSQL, and more.',  githubUrl:'https://github.com/sqlmapproject/sqlmap',                  demoUrl:null,                                              gradient:'linear-gradient(135deg,#7c2d12,#5e2209)', order:2 },
  { name:'Burp Suite',      icon:'🕷️', category:'Web Security',       language:'Java',       stars:'4.2k',  description:'Industry-standard web app security platform — intercept proxy, scanner, intruder, and repeater.',          githubUrl:'https://github.com/PortSwigger/burp-extensions-montoya-api', demoUrl:'https://portswigger.net/burp/communitydownload', gradient:'linear-gradient(135deg,#431407,#321005)', order:3 },
  { name:'OWASP ZAP',       icon:'🕸️', category:'Web Security',       language:'Java',       stars:'12.5k', description:'Free, open-source web app scanner. Best for beginners and CI/CD pipeline integration.',                    githubUrl:'https://github.com/zaproxy/zaproxy',                      demoUrl:'https://www.zaproxy.org',                         gradient:'linear-gradient(135deg,#0f3460,#0b2a52)', order:4 },
  { name:'Aircrack-ng',     icon:'📡', category:'Wireless',            language:'C',          stars:'4.9k',  description:'Complete WiFi security auditing suite — WEP and WPA/WPA2-PSK cracking, packet capture, and injection.',    githubUrl:'https://github.com/aircrack-ng/aircrack-ng',              demoUrl:'https://aircrack-ng.org',                         gradient:'linear-gradient(135deg,#3b0764,#2e0550)', order:5 },
  { name:'Hashcat',         icon:'🔐', category:'Password',            language:'C',          stars:'21.7k', description:'World\'s fastest password recovery. 300+ hash types, GPU-accelerated — MD5, SHA, bcrypt, and WPA2.',       githubUrl:'https://github.com/hashcat/hashcat',                       demoUrl:'https://hashcat.net',                             gradient:'linear-gradient(135deg,#292524,#1c1917)', order:6 },
  { name:'John the Ripper', icon:'🔓', category:'Password',            language:'C',          stars:'9.8k',  description:'Fast, flexible password cracker that auto-detects hash types. Supports 100+ formats out of the box.',       githubUrl:'https://github.com/openwall/john',                         demoUrl:null,                                              gradient:'linear-gradient(135deg,#422006,#321805)', order:7 },
  { name:'THC Hydra',       icon:'🐍', category:'Brute Force',         language:'C',          stars:'10.5k', description:'Fastest network logon cracker — 50+ protocols: FTP, HTTP, HTTPS, SMB, SSH, MySQL, and more.',             githubUrl:'https://github.com/vanhauser-thc/thc-hydra',              demoUrl:null,                                              gradient:'linear-gradient(135deg,#14532d,#0f3d21)', order:8 },
  { name:'Nikto',           icon:'🎯', category:'Web Security',       language:'Perl',       stars:'8.9k',  description:'Open-source web server scanner — tests for 6,700+ dangerous files, outdated software, and misconfigs.',    githubUrl:'https://github.com/sullo/nikto',                           demoUrl:null,                                              gradient:'linear-gradient(135deg,#7f1d1d,#5a1313)', order:9 },
  { name:'Gobuster',        icon:'🚀', category:'Reconnaissance',      language:'Go',         stars:'10.2k', description:'Blazing-fast directory, DNS, vhost, and S3 bucket enumeration tool written in Go.',                        githubUrl:'https://github.com/OJ/gobuster',                           demoUrl:null,                                              gradient:'linear-gradient(135deg,#065f46,#044f3a)', order:10 },
  { name:'Nuclei',          icon:'⚡', category:'Vuln Scanner',        language:'Go',         stars:'21.3k', description:'Template-based vulnerability scanner with 9,000+ community templates covering CVEs, misconfigs, and more.', githubUrl:'https://github.com/projectdiscovery/nuclei',              demoUrl:'https://nuclei.projectdiscovery.io',              gradient:'linear-gradient(135deg,#713f12,#5a320e)', order:11 },
  { name:'Subfinder',       icon:'🌐', category:'Reconnaissance',      language:'Go',         stars:'10.4k', description:'Passive subdomain discovery using 40+ sources — Shodan, VirusTotal, Censys, SecurityTrails, and more.',    githubUrl:'https://github.com/projectdiscovery/subfinder',           demoUrl:null,                                              gradient:'linear-gradient(135deg,#1e3a8a,#1a3270)', order:12 },
  { name:'Amass',           icon:'🗺️', category:'Reconnaissance',      language:'Go',         stars:'12.1k', description:'OWASP attack surface mapping — DNS enumeration, scraping, certificate transparency, and graph analysis.',   githubUrl:'https://github.com/owasp-amass/amass',                    demoUrl:null,                                              gradient:'linear-gradient(135deg,#3b0764,#2e0550)', order:13 },
  { name:'BloodHound',      icon:'🩸', category:'Active Directory',    language:'TypeScript', stars:'10.7k', description:'Reveal hidden AD attack paths using graph theory. Find the shortest route to Domain Admin.',                githubUrl:'https://github.com/BloodHoundAD/BloodHound',              demoUrl:null,                                              gradient:'linear-gradient(135deg,#7f1d1d,#5a1313)', order:14 },
  { name:'Impacket',        icon:'📦', category:'Exploitation',       language:'Python',     stars:'14.2k', description:'Python library for working with network protocols — DCE/RPC, SMB, LDAP. Essential for Windows pentesting.', githubUrl:'https://github.com/fortra/impacket',                       demoUrl:null,                                              gradient:'linear-gradient(135deg,#1e3a8a,#1a3270)', order:15 },
  { name:'Responder',       icon:'🎣', category:'Network',             language:'Python',     stars:'5.4k',  description:'LLMNR, NBT-NS, and MDNS poisoner — captures NTLMv2 hashes transparently on local network segments.',       githubUrl:'https://github.com/lgandx/Responder',                      demoUrl:null,                                              gradient:'linear-gradient(135deg,#7c2d12,#5e2209)', order:16 },
  { name:'Volatility 3',    icon:'🧠', category:'Forensics',           language:'Python',     stars:'2.9k',  description:'Advanced memory forensics framework. Analyse RAM dumps from Windows, Linux, and macOS systems.',             githubUrl:'https://github.com/volatilityfoundation/volatility3',      demoUrl:null,                                              gradient:'linear-gradient(135deg,#3b0764,#2e0550)', order:17 },
  { name:'Wireshark',       icon:'🦈', category:'Network',             language:'C',          stars:'7.3k',  description:'World\'s leading network protocol analyser — capture, inspect, and dissect traffic in real-time.',           githubUrl:'https://github.com/wireshark/wireshark',                   demoUrl:'https://www.wireshark.org',                       gradient:'linear-gradient(135deg,#1e3a8a,#1a3270)', order:18 },
  { name:'ffuf',            icon:'💨', category:'Web Security',       language:'Go',         stars:'13.4k', description:'Fuzz Faster U Fool — blindingly fast web fuzzer for directory discovery, parameter fuzzing, and vhosts.',   githubUrl:'https://github.com/ffuf/ffuf',                             demoUrl:null,                                              gradient:'linear-gradient(135deg,#065f46,#044f3a)', order:19 },
  { name:'PEASS-ng',        icon:'🐦', category:'Priv Escalation',     language:'Shell',      stars:'16.8k', description:'linPEAS & winPEAS — automated scripts to find local privilege escalation vectors on Linux and Windows.',    githubUrl:'https://github.com/carlospolop/PEASS-ng',                  demoUrl:null,                                              gradient:'linear-gradient(135deg,#14532d,#0f3d21)', order:20 },
  { name:'Sherlock',        icon:'🔎', category:'OSINT',               language:'Python',     stars:'18.9k', description:'Hunt down social media accounts by username across 400+ sites in seconds.',                               githubUrl:'https://github.com/sherlock-project/sherlock',            demoUrl:null,                                              gradient:'linear-gradient(135deg,#292524,#1c1917)', order:21 },
  { name:'theHarvester',    icon:'🌾', category:'OSINT',               language:'Python',     stars:'11.0k', description:'Gather emails, subdomains, hosts, and names from public sources. The go-to early-recon tool.',             githubUrl:'https://github.com/laramies/theHarvester',                demoUrl:null,                                              gradient:'linear-gradient(135deg,#14532d,#0f3d21)', order:22 },
  { name:'WPScan',          icon:'🔒', category:'Web Security',       language:'Ruby',       stars:'8.5k',  description:'WordPress vulnerability scanner — 36,000+ known vulnerabilities in WP core, plugins, and themes.',          githubUrl:'https://github.com/wpscanteam/wpscan',                     demoUrl:'https://wpscan.com',                              gradient:'linear-gradient(135deg,#7f1d1d,#5a1313)', order:23 },
  { name:'Mimikatz',        icon:'🗝️', category:'Credential Access',   language:'C',          stars:'19.2k', description:'Post-exploitation credential dumper — extracts plaintext passwords, hashes, and Kerberos tickets from LSASS.', githubUrl:'https://github.com/gentilkiwi/mimikatz',               demoUrl:null,                                              gradient:'linear-gradient(135deg,#292524,#1c1917)', order:24 },
];

export async function POST(req: NextRequest) {
  if (!isAdmin(req)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  try {
    let seeded = 0;
    for (const t of TOOLS) {
      await prisma.securityTool.upsert({
        where: { name: t.name },
        update: {},
        create: { ...t, demoUrl: t.demoUrl ?? undefined },
      });
      seeded++;
    }
    return NextResponse.json({ ok: true, seeded });
  } catch (err) {
    console.error(err);
    return NextResponse.json({ error: 'Seed failed' }, { status: 500 });
  }
}
